# Generated by Django 4.2.11 on 2025-12-25 11:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория номера',
                'verbose_name_plural': 'Категории номеров',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='Номер комнаты')),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Вместимость (человек)')),
                ('has_child_bed', models.BooleanField(default=False, verbose_name='Возможность детской кровати')),
                ('status', models.CharField(choices=[('available', 'Доступен'), ('booked', 'Забронирован'), ('occupied', 'Занят'), ('maintenance', 'На обслуживании')], default='available', max_length=20, verbose_name='Статус')),
                ('description', models.TextField(blank=True, verbose_name='Описание номера')),
                ('price_monday', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за понедельник')),
                ('price_tuesday', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за вторник')),
                ('price_wednesday', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за среду')),
                ('price_thursday', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за четверг')),
                ('price_friday', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за пятницу')),
                ('price_saturday', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за субботу')),
                ('price_sunday', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за воскресенье')),
                ('child_bed_price', models.DecimalField(decimal_places=2, default=500, max_digits=10, verbose_name='Цена детской кровати (за сутки)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rooms.roomcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
                'ordering': ['number'],
            },
        ),
    ]
